import type { CreateWordPairPayload } from '../../../../shared/types/words'

export const classiquePairs: CreateWordPairPayload[] = [
  { theme: 'classique', civilWord: 'chat', impostorWord: 'chien' },
  { theme: 'classique', civilWord: 'pomme', impostorWord: 'poire' },
  { theme: 'classique', civilWord: 'voiture', impostorWord: 'camion' },
  { theme: 'classique', civilWord: 'chaise', impostorWord: 'tabouret' },
  { theme: 'classique', civilWord: 'livre', impostorWord: 'magazine' },
  { theme: 'classique', civilWord: 'soleil', impostorWord: 'lune' },
  { theme: 'classique', civilWord: 'piscine', impostorWord: 'mer' },
  { theme: 'classique', civilWord: 'vélo', impostorWord: 'trottinette' },
  { theme: 'classique', civilWord: 'pizza', impostorWord: 'quiche' },
  { theme: 'classique', civilWord: 'café', impostorWord: 'thé' },
  { theme: 'classique', civilWord: 'fenêtre', impostorWord: 'porte' },
  { theme: 'classique', civilWord: 'lion', impostorWord: 'tigre' },
  { theme: 'classique', civilWord: 'océan', impostorWord: 'lac' },
  { theme: 'classique', civilWord: 'montagne', impostorWord: 'colline' },
  { theme: 'classique', civilWord: 'avion', impostorWord: 'hélicoptère' },
  { theme: 'classique', civilWord: 'banane', impostorWord: 'mangue' },
  { theme: 'classique', civilWord: 'lampe', impostorWord: 'bougie' },
  { theme: 'classique', civilWord: 'stylo', impostorWord: 'crayon' },
  { theme: 'classique', civilWord: 'montre', impostorWord: 'horloge' },
  { theme: 'classique', civilWord: 'téléphone', impostorWord: 'tablette' },
  { theme: 'classique', civilWord: 'train', impostorWord: 'métro' },
  { theme: 'classique', civilWord: 'grenouille', impostorWord: 'crapaud' },
  { theme: 'classique', civilWord: 'chapeau', impostorWord: 'casquette' },
  { theme: 'classique', civilWord: 'table', impostorWord: 'bureau' },
  { theme: 'classique', civilWord: 'manteau', impostorWord: 'veste' },
  { theme: 'classique', civilWord: 'nuage', impostorWord: 'brouillard' },
  { theme: 'classique', civilWord: 'forêt', impostorWord: 'jungle' },
  { theme: 'classique', civilWord: 'mouton', impostorWord: 'chèvre' },
  { theme: 'classique', civilWord: 'cerise', impostorWord: 'fraise' },
  { theme: 'classique', civilWord: 'beurre', impostorWord: 'margarine' },
  { theme: 'classique', civilWord: 'pain', impostorWord: 'brioche' },
  { theme: 'classique', civilWord: 'escalier', impostorWord: 'ascenseur' },
]
